
FROM node:12-alpine as builder

USER node
RUN mkdir /home/node/app
WORKDIR /home/node/app

EXPOSE 6006
ARG ENV=development
ENV NODE_ENV $ENV


COPY --chown=node:node package.json ./package.json
COPY --chown=node:node package-lock.json ./package-lock.json

RUN npm ci 
COPY --chown=node:node . .

RUN npx build-storybook -o ./build/storybook --quiet   

FROM halverneus/static-file-server

ENV PORT=6006
ENV FOLDER=/storybook

COPY --from=builder /home/node/app/build/storybook /storybook