apiVersion: skaffold/v2beta8
kind: Config
# build:
#   artifacts:
#     - image: trivia-night-frontend
#       context: frontend
#     - image: trivia-night-backend
#       context: backend
#     - image: trivia-night-hasura
#       context: hasura

profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubectl:
        manifests:
          - k8s/generated/*.yaml
    build:
      local:
        useBuildkit: true
      artifacts:
        - image: trivia-night-frontend
          context: frontend
          docker:
            dockerfile: Dockerfile.dev
            buildArgs:
              ENV: development
              NEXT_PUBLIC_TODO_APP_BACKEND_URL: http://hasura.{{.BASE_HOST}}/v1/graphql
              NEXT_PUBLIC_TODO_APP_BACKEND_WEBSOCKET_URL: ws://hasura.{{.BASE_HOST}}/v1/graphql
          sync:
            manual:
              - src: "src/**/*"
                dest: .
        - image: trivia-night-backend
          context: backend
        - image: trivia-night-hasura
          context: hasura/dev-dockerfile
        - image: trivia-night-storybook
          context: frontend
          docker:
            dockerfile: Dockerfile.storybook.dev
          sync:
            manual:
              - src: "src/**/*"
                dest: .
  - name: prod
    activation:
      - command: prod
    deploy:
      kubectl:
        manifests:
          - k8s/generated/*.yaml
    build:
      local:
        useBuildkit: true
      artifacts:
        - image: trivia-night-frontend
          context: frontend
          docker:
            buildArgs:
              # ENV: production
              NEXT_PUBLIC_TODO_APP_BACKEND_URL: http://hasura.{{.BASE_HOST}}/v1/graphql
              NEXT_PUBLIC_TODO_APP_BACKEND_WEBSOCKET_URL: ws://hasura.{{.BASE_HOST}}/v1/graphql
        - image: trivia-night-backend
          context: backend
        - image: trivia-night-hasura
          context: hasura
        - image: trivia-night-storybook
          context: frontend
          docker:
            dockerfile: Dockerfile.storybook

