# This lives in a seperate folder (dev-dockerfile) so that changes made in the console (written to migrations) don't trigger a rebuild in skaffold
# 
# To migrate, run migrations with the CLI (npm run migrate)
FROM hasura/graphql-engine:v1.3.2