apiVersion: v1
kind: Service
metadata:
  name: trivia-night-grafana
spec:
  ports:
    - port: 8082
      targetPort: 3000
  selector:
    app: trivia-night-grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivia-night-grafana
spec:
  selector:
    matchLabels:
      app: trivia-night-grafana
  template:
    metadata:
      labels:
        app: trivia-night-grafana
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: trivia-night-grafana
          image: grafana/grafana
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "32Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
